export type OrgRole = "OWNER" | "ADMIN" | "MANAGER" | "EMPLOYEE";

export const OrgRolePages: Record<OrgRole, string[]> = {
  OWNER: [
    "/",
    "/projects",
    "/clients",
    "/members",
    "/tags",
    "/reporting",
    "/reporting/overview",
    "/reporting/detailed",
    "/teams/:orgId",
    "/project/:id",
    "/settings",
    "/time",
    "/reporting/shared",
  ],
  ADMIN: [
    "/",
    "/projects",
    "/clients",
    "/members",
    "/tags",
    "/reporting",
    "/reporting/overview",
    "/reporting/detailed",
    "/teams/:orgId",
    "/project/:id",
    "/settings",
    "/time",
    "/reporting/shared",
  ],
  MANAGER: [
    "/",
    "/projects",
    "/clients",
    "/members",
    "/tags",
    "/reporting",
    "/project/:id",
    "/reporting/overview",
    "/reporting/detailed",
    "/time",
    "/reporting/shared",
  ],
  EMPLOYEE: [
    "/",
    "/projects",
    "/reporting",
    "/project/:id",
    "/reporting/overview",
    "/reporting/detailed",
    "/time",
    "/tags",
  ],
};

export const OrgRoleApiPermissions: Record<OrgRole, string[]> = {
  OWNER: [
    "createProject",
    "editProject",
    "deleteProject",
    "viewAllTimeEntries",
    "viewMembers",
    "viewInvite",
    "viewProjects",
    "inviteMember",
    "editMember",
    "deleteMember",
    "deleteInvite",
    "transferOwnership",
    "createClient",
    "viewClients",
    "editClient",
    "deleteClient",
    "viewProjectMembers",
    "viewTags",
    "editTag",
    "deleteTag",
    "taskview",
    "taskcreate",
    "taskedit",
    "saveReport",
  ],
  ADMIN: [
    "createProject",
    "editProject",
    "deleteProject",
    "inviteMember",
    "viewAllTimeEntries",
    "editMember",
    "deleteMember",
    "viewProjects",
    "deleteInvite",
    "viewInvite",
    "viewMembers",
    "viewProjectMembers",
    "viewClients",
    "editClient",
    "deleteClient",
    "viewTags",
    "editTag",
    "deleteTag",
    "taskview",
    "taskcreate",
    "taskedit",
    "saveReport",
  ],
  MANAGER: [
    "createProject",
    "editProject",
    "viewMembers",
    "viewInvite",
    "deleteProject",
    "viewProjects",
    "viewProjectMembers",
    "viewAllTimeEntries",
    "viewClients",
    "editTag",
    "viewTags",
    "taskcreate",
    "taskview",
    "taskedit",
    "viewMembers",
    "saveReport",
  ],
  EMPLOYEE: ["viewAllTimeEntries", "taskview", "viewProjects", "viewTags"],
};
